#!/bin/bash
#
# Publish ADR - Publica um ADR especifico na GitHub Wiki
#
# Usage:
#   ./publish_adr.sh path/to/adr.yml    # Publica ADR especifico
#   ./publish_adr.sh --all              # Publica todos os ADRs
#

set -e

# Cores
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

log_success() { echo -e "${GREEN}[OK]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1" >&2; }

# Verificar argumentos
if [[ $# -eq 0 ]]; then
    echo "Usage: $0 <adr-path> | --all"
    exit 1
fi

# Obter repositorio
REPO=$(gh repo view --json nameWithOwner -q '.nameWithOwner' 2>/dev/null)
if [[ -z "$REPO" ]]; then
    log_error "Nao foi possivel detectar repositorio"
    exit 1
fi

# Criar diretorio temporario
WIKI_DIR=$(mktemp -d)
trap "rm -rf $WIKI_DIR" EXIT

# Clonar wiki
echo "Clonando wiki..."
if ! git clone "https://github.com/${REPO}.wiki.git" "$WIKI_DIR" 2>/dev/null; then
    log_error "Falha ao clonar wiki"
    exit 1
fi

mkdir -p "$WIKI_DIR/ADRs"

# Funcao para converter ADR
convert_adr() {
    local adr_file="$1"

    if [[ ! -f "$adr_file" ]]; then
        log_error "Arquivo nao encontrado: $adr_file"
        return 1
    fi

    local basename=$(basename "$adr_file" | sed 's/\.[^.]*$//')
    local output_file="$WIKI_DIR/ADRs/${basename}.md"

    python3 - "$adr_file" "$output_file" << 'EOF'
import sys
import yaml
from pathlib import Path

adr_file = sys.argv[1]
output_file = sys.argv[2]

try:
    with open(adr_file) as f:
        data = yaml.safe_load(f)

    adr_id = data.get('id', Path(adr_file).stem)
    title = data.get('title', 'Untitled')
    status = data.get('status', 'Proposed')
    context = data.get('context', '')
    decision = data.get('decision', '')
    consequences = data.get('consequences', {})

    md = []
    md.append(f"# {adr_id}: {title}")
    md.append("")
    md.append(f"**Status:** {status}")
    md.append("")
    md.append("## Context")
    md.append(context)
    md.append("")
    md.append("## Decision")
    md.append(decision)
    md.append("")
    md.append("## Consequences")
    if isinstance(consequences, dict):
        for key, items in consequences.items():
            md.append(f"### {key.title()}")
            for item in (items or []):
                md.append(f"- {item}")
    md.append("")
    md.append("---")
    md.append("*Generated by SDLC Agentico*")

    with open(output_file, 'w') as f:
        f.write('\n'.join(md))
except Exception as e:
    print(f"Error: {e}", file=sys.stderr)
    sys.exit(1)
EOF

    if [[ $? -eq 0 ]]; then
        log_success "Convertido: $basename"
        return 0
    else
        return 1
    fi
}

# Processar ADRs
if [[ "$1" == "--all" ]]; then
    echo "Publicando todos os ADRs..."

    for adr in .agentic_sdlc/corpus/nodes/decisions/*.yml \
               .agentic_sdlc/corpus/nodes/decisions/*.yaml \
               .agentic_sdlc/projects/*/decisions/*.yml \
               .agentic_sdlc/projects/*/decisions/*.yaml 2>/dev/null; do
        if [[ -f "$adr" ]]; then
            convert_adr "$adr"
        fi
    done
else
    convert_adr "$1"
fi

# Commit e push
cd "$WIKI_DIR"

if git diff --quiet && git diff --staged --quiet; then
    echo "Nenhuma mudanca para publicar"
    exit 0
fi

git add .
git commit -m "docs: publish ADR $(date +%Y-%m-%d)"

if git push; then
    log_success "ADR(s) publicado(s) na wiki"
    echo "URL: https://github.com/${REPO}/wiki"
else
    log_error "Falha ao publicar"
    exit 1
fi
